# Default DisGeNET prefixes.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX so: <http://www.sequenceontology.org/miso/current_svn/term/SO:>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX wi: <http://purl.org/ontology/wi/core#>
PREFIX eco: <http://purl.obolibrary.org/obo/eco.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pav: <http://purl.org/pav/>
PREFIX obo: <http://purl.obolibrary.org/obo/> 

# Custom prefixes.
PREFIX umls: <http://linkedlifedata.com/resource/umls/id/> # DisGeNET
PREFIX ncbigene: <http://identifiers.org/ncbigene/> # DisGeNET
PREFIX pda: <http://rdf.disgenet.org/resource/pda/> # DisGeNET
PREFIX gda: <http://rdf.disgenet.org/resource/gda/> # DisGeNET
PREFIX ordo: <http://www.orpha.net/ORDO/> # DisGeNET / Orphanet
PREFIX hoom: <http://www.semanticweb.org/ontology/HOOM#> # Orphanet
PREFIX void5: <http://rdf.disgenet.org/v5.0.0/void/> # DisGeNET
PREFIX void6: <http://rdf.disgenet.org/v6.0.0/void/> # DisGeNET

# Query.
CONSTRUCT {
	?gene rdf:type ncit:C16612 ;
	dcterms:identifier ?geneId ;
	sio:SIO_000205 ?symbolName ; # "is represented by"
	sio:SIO_001351 ?dsiValue ;
	sio:SIO_001352 ?dpiValue .
}
WHERE {
	?gene dcterms:identifier ?geneId ;
	sio:SIO_000205 ?symbol;
	sio:SIO_000216 ?dsi, ?dpi .
	?symbol dcterms:identifier ?symbolName .
	OPTIONAL { ?dsi sio:SIO_000300 ?dsiValue . } # some ncbigene's are missing this score
	OPTIONAL { ?dpi sio:SIO_000300 ?dpiValue . } # some ncbigene's are missing this score

	FILTER EXISTS {?gene rdf:type ncit:C16612}
	FILTER EXISTS {?symbol rdf:type ncit:C43568}
	FILTER EXISTS {?dsi rdf:type sio:SIO_001351}
	FILTER EXISTS {?dpi rdf:type sio:SIO_001352}
}
