# Default DisGeNET prefixes.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX so: <http://www.sequenceontology.org/miso/current_svn/term/SO:>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX wi: <http://purl.org/ontology/wi/core#>
PREFIX eco: <http://purl.obolibrary.org/obo/eco.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pav: <http://purl.org/pav/>
PREFIX obo: <http://purl.obolibrary.org/obo/> 

# Custom prefixes.
PREFIX umls: <http://linkedlifedata.com/resource/umls/id/> # DisGeNET
PREFIX ncbigene: <http://identifiers.org/ncbigene/> # DisGeNET
PREFIX pda: <http://rdf.disgenet.org/resource/pda/> # DisGeNET
PREFIX gda: <http://rdf.disgenet.org/resource/gda/> # DisGeNET
PREFIX ordo: <http://www.orpha.net/ORDO/> # DisGeNET / Orphanet
PREFIX hoom: <http://www.semanticweb.org/ontology/HOOM#> # Orphanet
PREFIX void5: <http://rdf.disgenet.org/v5.0.0/void/>
PREFIX void6: <http://rdf.disgenet.org/v6.0.0/void/>

# Query.
CONSTRUCT {
	?source rdf:type ?type ; # Some sources have extra RDF:type objects.
	wi:evidence ?sourceLevel ;
	dcterms:title ?sourceTitle .
}
WHERE {
	?source rdf:type ?type ;
	wi:evidence ?sourceLevel .
	{
		SELECT ?source (MAX(?sourceTitleGroup) AS ?sourceTitle) # Filters duplicate titles to only longest title.
		WHERE {
			?source rdf:type dctypes:Dataset , dcat:Distribution ; # Faster than using FILTER EXISTS.
			dcterms:title ?sourceTitleGroup .
		}
		GROUP BY ?source
	}

	?association sio:SIO_000253 ?source . # Makes sure only sources are present that are actually referred to (does increase runtime significantly).
}